spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/images
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
  profiles:
    active: den
server:
  port: 8009
---
spring:
  profiles: verification
  datasource:
    username: viktor
    password: 123456

---
 spring:
  profiles: working
  datasource:
    username: postgres
    password: root
---
  spring:
    profiles: den
    datasource:
      username: postgres
      password: postgres