spring:
  datasource:
    username: victor
    password: 123456
    url: jdbc:postgresql://localhost:5432/images
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
server:
  port: 8009